### ISSUE TITLE
Funções antes de todos os includes

### ISSUE THREAD

**Issue by eduardomarossi** [gabrielmou10/WashingMachine_Interface#2]
https://github.com/gabrielmou10/WashingMachine_Interface/blob/a75ef2303da512f6702c7cfc466f8aa4fdce0ad6/APS2/APS2/src/main.c#L108-L182

Ideal é funções virem por últimos depois de includes, defines, typedefs, protótipos, variáveis globais e então funções

**Comment by gabrielmou10** [comment]
OK!
