### ISSUE TITLE
Descobrir qual ciclo pelo tempo não é uma boa ideia, e se amanha mudar o tempo do ciclo?

### ISSUE THREAD

**Issue by eduardomarossi** [gabrielmou10/WashingMachine_Interface#6]
https://github.com/gabrielmou10/WashingMachine_Interface/blob/a75ef2303da512f6702c7cfc466f8aa4fdce0ad6/APS2/APS2/src/main.c#L404-L418

Poderia ter feito
`if(statusCiclo == c_enxague)'

**Comment by gabrielmou10** [comment]
OK!
