### ISSUE TITLE
Projeto não compila, por favor verificar

### ISSUE THREAD

**Issue by eduardomarossi** [gabrielmou10/WashingMachine_Interface#9]
Erros:

Severity | Code | Description | Project | File | Line
-- | -- | -- | -- | -- | --
Error |   | 'Diario' undeclared (first use in this function) | APS2 | C:\Projetos\APS2\WashingMachine_Interface\APS2\APS2\src\main.c | 408
Error |   | recipe for target 'src/main.o' failed | APS2 | C:\Projetos\APS2\WashingMachine_Interface\APS2\APS2\Debug\Makefile | 421
Error |   | redefinition of 'Centrifugacao' | APS2 | C:\Projetos\APS2\WashingMachine_Interface\APS2\APS2\src\icones\Centrifugacao.h | 83
Error |   | redefinition of 'image_data_Centrifugacao' | APS2 | C:\Projetos\APS2\WashingMachine_Interface\APS2\APS2\src\icones\Centrifugacao.h | 31

**Comment by gabrielmou10** [comment]
OK!
